# basic options
title: "Hey, I'm Tazdeedul Chowdhury"
author: GitHub User
email: tazdeed1@gmail.com
description: pepe wonderful
linkedin_username: tazdeedchowdhury
github_username: tazdeed

# Build Settings
markdown: kramdown
theme: minima

