# basic options
title: "Hey, I'm Tazdeed Chowdhury"
author: Tazdeed Chowowdhury
email: tazdeed1@gmail.com
description: pepe wonderful
linkedin_username: tazdeedchowdhury
github_username: tazdeed

# Build Settings
markdown: kramdown
theme: minima

