# Basic Options
title: Tazdeedul Chowdhury Portfolio
author: Tazdeed
email: tazdeed1@gmail.com
description: Hey, thank you for visiting my website! Please feel free to browse through my projects. 

# Build Settings
theme: jekyll-theme-hacker
