title: "Hi, I'm Tazdeedul Chowdhury"
author: "Tazdeedul Chowdhury"
description: "test" 

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "tazdeed1@gmail.com"
#twitter_username: "twitteruser"
github_username: "Tazdeed"
linkedin_username: "tazdeedchowdhury"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Build Settings
theme: "minima"
markdown: "kramdown"

